In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("IMDB Dataset.csv")

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [9]:
df.shape

(100, 2)

In [8]:
df=df.head(100)

PREPROCESSING

In [13]:
#lower case

df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [12]:
df['review']=df['review'].str.lower()

In [14]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. <br /><br />the...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

In [19]:
# remove html tags

import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [22]:
text= "basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them"

In [23]:
remove_html_tags(text)

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them"

In [24]:
df['review']= df['review'].apply(remove_html_tags)

In [26]:
df['review'][7]

"this show was an amazing, fresh & innovative idea in the 70's when it first aired. the first 7 or 8 years were brilliant, but things dropped off after that. by 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.it's truly disgraceful how far this show has fallen. the writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. i find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. how can one recognize such brilliance and then see fit to replace it with such mediocrity? i felt i must give 2 stars out of respect for the original cast that made this show such a huge success. as it is now, the show is just awful. i can't believe it's still on the air."

In [28]:
# remove url

def remove_url(text):
    pattern = re.compile('https?://\S+')
    return pattern.sub(r'', text)

In [31]:
text = "Check this out: https://example.com and also http://test.com"
remove_url(text)

'Check this out:  and also '

In [47]:
df['review']= df['review'].apply(remove_url)

In [32]:
# punctuation handling

import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
store=string.punctuation
store

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [34]:
def remove_punc(text):
    for char in store:
        text= text.replace(char,'')
    return text

In [40]:
text = "Hello, world! This is a test: does it work?"
remove_punc(text)

'Hello world This is a test does it work'

In [46]:
start= time.time()
print(remove_punc(text))

time1= time.time() -start
print(time1*50000)

Hello world This is a test does it work
54.955482482910156

In [43]:
#method 2

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [48]:
df['review']= df['review'].apply(remove_punc)

In [50]:
df['review'][3]

'basically theres a family where a little boy jake thinks theres a zombie in his closet  his parents are fighting all the timethis movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombieok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing  arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spots3 out of 10 just for the well playing parents  descent dialogs as for the shots with jake just ignore them'

CHAT_CONVERSATION_HANDLE

In [51]:
chat_acronyms = {
    # General / Conversation
    "FYI": "For Your Information",
    "BTW": "By The Way",
    "IMO": "In My Opinion",
    "IMHO": "In My Humble Opinion",
    "IDK": "I Don't Know",
    "IDC": "I Don't Care",
    "IRL": "In Real Life",
    "TL;DR": "Too Long; Didn't Read",

    # Affirmation / Agreement
    "LOL": "Laugh Out Loud",
    "LMAO": "Laughing My Ass Off",
    "ROFL": "Rolling On the Floor Laughing",
    "BRB": "Be Right Back",
    "GTG": "Got To Go",
    "G2G": "Got To Go",

    # Excitement / Fun
    "YOLO": "You Only Live Once",
    "OMG": "Oh My God",
    "OMW": "On My Way",
    "SMH": "Shaking My Head",
    "FML": "F*** My Life",
    "BFF": "Best Friends Forever",

    # Tech / Online
    "AFK": "Away From Keyboard",
    "DM": "Direct Message",
    "PM": "Private Message",
    "OP": "Original Poster",
    "FAQ": "Frequently Asked Questions",

    # Time / Planning
    "TTYL": "Talk To You Later",
    "TBA": "To Be Announced",
    "TBD": "To Be Decided",
    "ETA": "Estimated Time of Arrival",

    # Emotions / Reactions
    "XD": "Laughing face",
    "JK": "Just Kidding",
    "TBH": "To Be Honest",
    "ILY": "I Love You",
    "<3": "Heart",

    # Gaming / Internet Slang
    "GG": "Good Game",
    "WP": "Well Played",
    "NPC": "Non-Player Character",
    "AF": "As F*** (used for emphasis)",
}

In [56]:
abbrevation = "BTW"
print(f"{abbrevation}: {chat_acronyms.get(abbrevation, 'Not Found')}")

BTW: By The Way

In [74]:
# INCORRECT_TEXT HANDLING

!pip install language_tool_python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: language_tool_python in c:\users\amanp\appdata\roaming\python\python310\site-packages (3.2.2)
Requirement already satisfied: requests in c:\users\amanp\appdata\roaming\python\python310\site-packages (from language_tool_python) (2.32.5)
Requirement already satisfied: tqdm in c:\users\amanp\appdata\roaming\python\python310\site-packages (from language_tool_python) (4.67.3)
Requirement already satisfied: packaging in c:\users\amanp\appdata\roaming\python\python310\site-packages (from language_tool_python) (26.0)
Requirement already satisfied: psutil in c:\users\amanp\appdata\roaming\python\python310\site-packages (from language_tool_python) (7.2.2)
Requirement already satisfied: toml in c:\users\amanp\appdata\roaming\python\python310\site-packages (from language_tool_python) (0.10.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests->language_tool_python) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests->language_tool_python) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests->language_tool_python) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests->language_tool_python) (2026.1.4)
Requirement already satisfied: colorama in c:\users\amanp\appdata\roaming\python\python310\site-packages (from tqdm->language_tool_python) (0.4.6)

In [123]:
import language_tool_python

tool = language_tool_python.LanguageTool('en-US')

def correct_grammar(text):
    matches = tool.check(text)
    corrected_text = language_tool_python.utils.correct(text, matches)
    return corrected_text

In [122]:
df['review'] = df['review'].apply(correct_grammar)

In [87]:
# remove stopwords

# "I love this product" → important words: ["love", "product"]
# to remove noise, reduce dim, improve model performance

In [106]:
# stop_words = {
#     "i","me","my","myself","we","our","ours","ourselves","you","your","yours",
#     "yourself","yourselves","he","him","his","himself","she","her","hers","herself",
#     "it","its","itself","they","them","their","theirs","themselves","what","which",
#     "who","whom","this","that","these","those","am","is","are","was","were","be",
#     "been","being","have","has","had","having","do","does","did","doing","a","an",
#     "the","and","but","if","or","because","as","until","while","of","at","by","for",
#     "with","about","against","between","into","through","during","before","after",
#     "above","below","to","from","up","down","in","out","on","off","over","under",
#     "again","further","then","once","here","there","when","where","why","how","all",
#     "any","both","each","few","more","most","other","some","such","no","nor","not",
#     "only","own","same","so","than","too","very","s","t","can","will","just","don",
#     "should","now"
# }

# def remove_stopwords(text):
#     # Split by spaces and remove stopwords
#     words = text.split()
#     filtered_words = [w for w in words if w.lower() not in stop_words]
#     return ' '.join(filtered_words)

# # Test
# text = "This is an example sentence showing stopwords removal."
# clean_text = remove_stopwords(text)
# print(clean_text)

In [108]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\amanp\appdata\roaming\python\python310\site-packages (3.9.3)
Requirement already satisfied: click in c:\users\amanp\appdata\roaming\python\python310\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\amanp\appdata\roaming\python\python310\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from nltk) (2026.2.19)
Requirement already satisfied: tqdm in c:\users\amanp\appdata\roaming\python\python310\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\amanp\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)

In [111]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [115]:
len(stopwords.words('english'))

198

In [124]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    filtered = [word for word in text.split() if word.lower() not in stop_words]
    return ' '.join(filtered)

df['review'] = df['review'].apply(remove_stopwords)

In [126]:
# handle emoji

import re
tool = language_tool_python.LanguageTool('en-US')

def remove_emoji(text):
    emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F680-\U0001F6FF"  # transport & map symbols
    "\U0001F1E0-\U0001F1FF"  # flags
    "]+", flags=re.UNICODE
)
    return emoji_pattern.sub(r'',text)

In [131]:
text = "He dont lika pizza 🍕 but hea eats it alway 😂"
corrected = remove_emoji(text)
print("Original:", sample_text)
print("Corrected:", corrected)

Original: He dont lika pizza 🍕 but hea eats it alway 😂
Corrected: He dont lika pizza  but hea eats it alway

In [132]:
!pip install emoji

Defaulting to user installation because normal site-packages is not writeable
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 608.4/608.4 kB 7.4 MB/s  0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [135]:
import emoji
print(emoji.demojize('i am 😂'))

i am :face_with_tears_of_joy:

TOKENIZATION

In [137]:
# using the split func


#word tokenization
sent1="I am going to home"
sent1.split()

['I', 'am', 'going', 'to', 'home']

In [138]:
# sentence tokenization
sent2= "I am going to home. I will stay for 3 days"
sent2.split('.')

['I am going to home', ' I will stay for 3 days']

In [150]:
# using NLTK

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

text = "He doesn't like pizza 🍕."
tokens = word_tokenize(text)

print(tokens)

['He', 'does', "n't", 'like', 'pizza', '🍕', '.']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\amanp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [151]:
text = "He doesnot like pizza 🍕."
tokens = word_tokenize(text)

print(tokens)

['He', 'doesnot', 'like', 'pizza', '🍕', '.']

In [154]:
# using spacy

!pip install spacy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: spacy in c:\users\amanp\appdata\roaming\python\python310\site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (2.2.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\program files\python310\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\amanp\appdata\roaming\python\python310\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: typer>=0.24.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: wrapt in c:\users\amanp\appdata\roaming\python\python310\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)
Requirement already satisfied: click>=8.2.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (14.3.1)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\amanp\appdata\roaming\python\python310\site-packages (from jinja2->spacy) (3.0.3)

In [156]:
!python -m spacy download en_core_web_sm

Defaulting to user installation because normal site-packages is not writeable
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ------------- -------------------------- 4.2/12.8 MB 21.0 MB/s eta 0:00:01
     -------------------------- ------------- 8.4/12.8 MB 20.8 MB/s eta 0:00:01
     ----------------------------------- --- 11.8/12.8 MB 18.9 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 17.1 MB/s  0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [157]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "He doesn't like pizza 🍕."
doc = nlp(text)
tokens = [token.text for token in doc]

print(tokens)

['He', 'does', "n't", 'like', 'pizza', '🍕', '.']

In [158]:
# NLTK uses rule-based tokenizers.
# spaCy uses optimized pipeline-based tokenization.

In [163]:
#Stemmer

# stemmer is a tool in NLP that reduces a word to its base/root form
# removes suffixes like:-ing,-ed,-ly etc

from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

words = ["playing", "played", "studies", "happiness"]

for word in words:
    print(word, "→", stemmer.stem(word))

playing → play
played → play
studies → studi
happiness → happi

In [179]:
# stemmer many a times does give the right word that are human readable -> thats why  use lemmatization
# eg : happiness → happi

In [191]:
# lemmatization  -> Lemmatization is the process of reducing a word to its base or dictionary form, called a lemma.
import spacy
from nltk.corpus import wordnet
import language_tool_python
import nltk

# Load tools
nlp = spacy.load("en_core_web_sm")
tool = language_tool_python.LanguageTool('en-US')

def noun_to_adj(word):
    """
    Enhanced: Checks for pertainyms AND derivationally related adjectives.
    """
    syns = wordnet.synsets(word.lower(), pos=wordnet.NOUN)
    for s in syns:
        for lemma in s.lemmas():
            # 1. Your original Pertainym check
            for pertainym in lemma.pertainyms():
                return pertainym.name().replace("_", " ")
            
            # 2. NEW: Check for derivationally related forms that are Adjectives
            for drf in lemma.derivationally_related_forms():
                if drf.synset().pos() in ['a', 's']: # 'a' = adj, 's' = satellite adj
                    return drf.name().replace("_", " ")
    return word

def smart_lemmatize(text):
    doc = nlp(text)
    tokens = []
    for token in doc:
        if token.pos_ == "NOUN":
            # Pass the lemma (e.g., 'happiness') to the converter
            lemma = noun_to_adj(token.lemma_)
        else:
            lemma = token.lemma_
        tokens.append(lemma)
    
    lemmatized_text = " ".join(tokens)
    matches = tool.check(lemmatized_text)
    return language_tool_python.utils.correct(lemmatized_text, matches)

text = "He was feeling happiness"
print(smart_lemmatize(text))

He is felt happy

In [192]:
text = "happiness "
print(smart_lemmatize(text))

happy

In [ ]:
# Stemming : Rule-based chopping ,fast
# Lemmatization : Dictionary + POS + grammar aware ,slow